version: '3.8'
services:
  portfolio:
    image: rothana01/portfolio:1.0
    # deploy:
    #   replicas: 1
    #   placement:
    #     constraints: [node.role == manager]
    networks:
      - proxy

networks:
  proxy:
    external: true
