version: '3.8'

services:
  database:
    image: mysql:8.0
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
    networks:
      - proxy

  wordpress:
    image: wordpress:latest
    volumes:
      - ./wordpress:/var/www/html/
    depends_on:
      - database
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
    networks:
      - proxy

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress
    networks:
      - proxy

networks:
    proxy:
      internal: true